SUNews/Areas/Admin/Controllers/UserController.cs
namespace SUNews.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using SUNews.Areas.Admin.Models;
    using SUNews.Data.Models;
    using SUNews.Providers;
    using SUNews.Services.Constants;
    using SUNews.Services.Contracts;
    using X.PagedList;

    [Area("Admin")]
    [Authorize(Roles = "Administrator")]
    public class UserController : Controller
    {
        private readonly IRoleManager<IdentityRole> roleManager;
        private readonly IUserManager<User> userManager;
        private readonly IRolesProvider createRolesProvider;

        private readonly int PAGE_SIZE = 3;

        public UserController(IRoleManager<IdentityRole> _roleManager,
                              IUserManager<User> _userManager,
        IRolesProvider _createRolesProvider)
        {
            roleManager = _roleManager;
            userManager = _userManager;
            createRolesProvider = _createRolesProvider;
        }


        public async Task<IActionResult> Index()
        {
            var allUsers = userManager.Users.ToList();

            var model = new UserIndexViewModel(allUsers, 1, PAGE_SIZE);

            return View(model);
        }

        public IActionResult UserGrid(int? page)
        {
            var pagedUsers = userManager.Users
                                         .Select(u => new AllUsersViewModel(u))
                                         .ToPagedList(page ?? 1, PAGE_SIZE);

            return PartialView("_UserGrid", pagedUsers);
        }

        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateRole(string role)
        {

            if (!ModelState.IsValid)
            {
                ViewData[MessageConstant.ErrorMessage] = $"Please submit correct value!";

                return View(role);
            }

            var result = await createRolesProvider.CreateRole(role);

            ViewData[result.Item1] = result.Item2;

            return View();
        }


        //[Authorize(Roles = "Administrator")]
        //[Authorize(Roles = "Owner")]
        //[Authorize(Roles = "Manager")]
        //public async Task<IActionResult> GetAllAdmins()
        //{
        //    var allAdmins = await userManager.GetUsersInRoleAsync("Administrator");


        //    return View("Users", allAdmins);
        //}

        public async Task<IActionResult> Details(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user is null)
            {
                RedirectToAction(nameof(Index));
            }

            var userRoles = await userManager.GetRolesAsync(user);

            var userViewModel = new UserDetailsViewModel(user);

            userViewModel.Role = String.Join(", ", userRoles);

            return View(userViewModel);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var idetityUser = await userManager.FindByIdAsync(id);

            var roles = roleManager.Roles;
            var userRoles = await userManager.GetRolesAsync(idetityUser);


            var model = new UserEditViewModel(idetityUser);
            model.Roles = userRoles;
            model.RolesList = roles.Select(r => new SelectListItem { Text = r.Name, Value = r.Name }).ToList();

            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Edit", new { id = model.Id });
            }

            var user = await userManager.FindByIdAsync(model.Id);
            var userRoles = await userManager.GetRolesAsync(user);


            var removeUserRoles = await userManager.RemoveFromRolesAsync(user, userRoles);


            var addUserToRoles = await userManager.AddToRolesAsync(user, model.Roles);
            if (!addUserToRoles.Succeeded)
            {
                return RedirectToAction("Edit", new { id = model.Id });
            }
            // Исках да вкарам повече фунцконалност с промянва на Firstname, Lastname and ect, но нямма време!

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LockUser(string id)
        {
            var user = userManager.Users.Where(u => u.Id == id).FirstOrDefault();
            if (user is null)
            {
                return this.RedirectToAction(nameof(Index));
            }

            var enableLockOutResult = await userManager.SetLockoutEnabledAsync(user, true);
            if (!enableLockOutResult.Succeeded)
            {
                return this.RedirectToAction(nameof(Index));
            }
            var lockoutTimeResult = await userManager.SetLockoutEndDateAsync(user, DateTime.Today.AddYears(10));
            if (!lockoutTimeResult.Succeeded)
            {
                return this.RedirectToAction(nameof(Index));
            }
            return this.RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnlockUser(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user is null)
            {
                return this.RedirectToAction(nameof(Index));
            }

            var lockoutTimeResult = await userManager.SetLockoutEndDateAsync(user, null);
            if (!lockoutTimeResult.Succeeded)
            {
                return this.RedirectToAction(nameof(Index));
            }
            return this.RedirectToAction(nameof(Index));
        }
    }
}

SUNews/Controllers/ArticleController.cs
namespace SUNews.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using SUNews.Data.Models;
    using SUNews.Models;
    using SUNews.Providers;
    using SUNews.Services.Constants;
    using SUNews.Services.Contracts;
    using SUNews.Services.Models;

    public class ArticleController : Controller
    {
        private readonly IArticleService articleService;
        private readonly ICategoryService categoryService;
        private readonly IUserManager<User> userManager;

        public ArticleController(IArticleService _articleService,
                                 ICategoryService _categoryService,
                                 IUserManager<User> _userManager)
        {
            this.articleService = _articleService;
            this.userManager = _userManager;
        }


        public async Task<IActionResult> Index()
        {
            var articles = await articleService.GetAllArticlesAsync();

            return View(articles);
        }

        public IActionResult AllArticles()
        {
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> DetailsOfArticle(string id)
        {
            try
            {
                var article = await articleService.DetailsOfArticleAsync(id);
                var comment = new CreateCommentViewModel();

                return View(new ArticleAndCommentsViewModel() { DetailsOfArticlesServiceModel = article, CreateCommentViewModel = comment });
            }
            catch (Exception)
            {

                return RedirectToAction(nameof(Index));

            }

        }

        public async Task<IActionResult> LikeArticle(string id)
        {
            try
            {
                var loggedUser = await userManager.GetUserAsync(User);
                var article = await articleService.LikeArticleAsync(id, loggedUser.Id);

                return RedirectToAction("DetailsOfArticle", new { Id = id });
            }
            catch (Exception)
            {
                return NotFound();
            }
        }
    }
}

SUNews/Controllers/CategoryController.cs
namespace SUNews.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using SUNews.Models;
    using SUNews.Services.Contracts;
    using SUNews.Services.Models;

    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoryController(ICategoryService _categoryService)
        {
            categoryService = _categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await categoryService.AllCategories();


            var model = new CategoriesAndArticlesViewModel()
            {
                Categories = categories
            };

            return View(model);
        }

        public async Task<IActionResult> Category(string id)
        {   
            try
            {
                var allArticlesByCategory = await categoryService.GetArticlesByCategory(id);

                var model = allArticlesByCategory;

                return PartialView("_CategoryArticleGrid", model);
            }
            catch (Exception)
            {

                return NotFound();
            }
            
        }
    }
}

SUNews/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SUNews.Data.Models;
using SUNews.Models;
using SUNews.Providers;
using SUNews.Services.Contracts;

namespace SUNews.Web.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService commentService;
        private readonly IUserManager<User> userManager;


        public CommentController(ICommentService _commentService, IUserManager<User> _userManager)
        {
            commentService = _commentService;
            userManager = _userManager;
        }

        [Authorize]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateComment(CreateCommentViewModel createCommentViewModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(createCommentViewModel.CurrentAction, createCommentViewModel.CurrentController, new { id = createCommentViewModel.ArticleId });
            }

            var user = await userManager.GetUserAsync(User);
            await commentService.CreateCommentAsync(createCommentViewModel.Text, createCommentViewModel.ArticleId, user.Id);

            return RedirectToAction(createCommentViewModel.CurrentAction, createCommentViewModel.CurrentController, new { id = createCommentViewModel.ArticleId });
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> DeleteComment(int id, string articleId)
        {
            try
            {
                await commentService.DeleteCommentAsync(id);
            }
            catch (Exception)
            {
                ViewData["ErrorMessage"] = "Sorry but something went wrong.";

                return RedirectToAction("DetailsOfArticle", "Article", new { id = articleId });
            }

            return RedirectToAction("DetailsOfArticle", "Article", new { id = articleId });
        }

        [HttpPost]
        [Authorize]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> ReportComment(int id, string articleId)
        {
            try
            {
                await commentService.ReportCommentAsync(id);
            }
            catch (Exception)
            {
                ViewData["ErrorMessage"] = "Sorry but something went wrong.";

                return RedirectToAction("DetailsOfArticle", "Article", new { id = articleId });
            }

            return RedirectToAction("DetailsOfArticle", "Article", new { id = articleId });
        }
    }
}

SUNews/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - SUNews</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css" />
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.min.css" />
    <link rel="stylesheet" href="~/plugins/toastr/toastr.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @await RenderSectionAsync("Head", false)
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Article" asp-action="CreateArticle">
                        <i class="fas fa-plus"></i>
                        CreateArticle
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Category" asp-action="CreateCategory" class="nav-link text-dark">
                        <i class="fas fa-hashtag"></i>
                        Create Category
                    </a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <partial name="_LoginPartial" />
                </li>
            </ul>
        </nav>

        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a asp-area="" asp-controller="Article" asp-action="Index" class="brand-link">
                <span class="brand-text font-weight-light">My SUNews</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/img/avatar5.png" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a class="d-block" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@User.Identity.Name</a>
                    </div>
                </div>
                <!-- Sidebar Menu -->
                <partial name="_MainMenu" />
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    <br />
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; @DateTime.Now.Year <a href="">My SUNews</a></strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <partial name="_UserMessages" />
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

SUNews/Areas/Admin/Views/Shared/_ArticleGrid.cshtml
@model AllArticlesServiceModel

<td>
    <a>
        @Model.Title
    </a>
</td>
<td>
    <ul class="list-inline text-center">
        <li class="list-inline-item">
            @Model.DateOfCreation.ToLongDateString()
        </li>
    </ul>
</td>
<td class="project-state">
    <span class="text-center">@Model.AuthorName</span>
</td>
<td class="project-actions text-right">
    <form asp-area="Admin" asp-controller="Article" asp-action="EditArticle" asp-route-id="@Model.Id" method="get">
        <button type="submit" class="btn btn-info btn-sm">
            <i class="fas fa-edit"></i>
            Edit
        </button>
    </form>
    <br />
    <form asp-area="Admin" asp-controller="Article" asp-action="DeleteArticle" asp-route-id="@Model.Id" method="post">
        <button type="submit" class="btn btn-danger btn-sm">
            Delete
        </button>
    </form>
</td>

SUNews/Areas/Admin/Views/Shared/_CommentGrid.cshtml
@model CommentServiceModel

<td>
    <a>
        @Model.Text
    </a>
</td>
<td>
    <ul class="list-inline text-center">
        <li class="list-inline-item">
            @Model.DateOfCreation
        </li>
    </ul>
</td>
<td class="project-state">
    <span class="text-center">@Model.UserName</span>
</td>
<td class="project-actions text-right">
    <form asp-area="Admin" asp-controller="Comment" asp-action="DeleteReport" asp-route-id="@Model.Id" method="post">
        <button type="submit" class="btn btn-info btn-sm">
            <i class="fas fa-exclamation-circle"></i> Delete Report
        </button>
    </form>
    <br />
    <form asp-area="Admin" asp-controller="Comment" asp-action="DeleteComment" asp-route-id="@Model.Id" method="post">
        <button type="submit" class="btn btn-danger btn-sm">
            <i class="fas fa-comment-alt"></i> Delete Comment
        </button>
    </form>
</td>

SUNews/Areas/Admin/Views/Shared/_MainMenu.cshtml
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->


        <li class="nav-item">
            <a asp-area="Admin" asp-controller="User" asp-action="Index" class="nav-link">
                <i class="fas fa-users"></i>
                <p>User Manager</p>
            </a>
        </li>
        <li class="nav-item">
            <a asp-area="Admin" asp-controller="Article" asp-action="AllArticles" class="nav-link">
                <i class="fas fa-newspaper"></i>
                <p>Article Manager</p>
            </a>
        </li>
        <li class="nav-item">
            <a asp-area="Admin" asp-controller="Comment" asp-action="AllReportedComment" class="nav-link">
                <i class="fas fa-comments"></i>
                <p>Comment Manager</p>
            </a>
        </li>
    </ul>
</nav>

SUNews/Areas/Admin/Views/Shared/_UserGrid.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core

@model IPagedList<AllUsersViewModel>
<!-- Site wrapper -->
<div class="wrapper" id="content">
    <!-- Navbar -->
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><i class="fas fa-users"></i> Users</h3>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Name
                            </th>
                            <th style="width: 30%">
                                Email address
                            </th>
                            <th style="width: 8%" class="text-center">
                                Status
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (var i = 0; i < @Model.Count; i++)
                        {
                            <tr>
                                <td>
                                    @(i + 1)
                                <td>
                                    <a>
                                            @Model[i].Name
                                    </a>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                                @Model[i].Email
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                        @{
                                            if (@Model[i].LockoutEnd is not null)
                                            {
                                            <span class="badge badge-danger">Locked</span>
                                            <br />
                                            <small> till @Model[i].LockoutEnd </small>
                                            }
                                            else
                                            {
                                            <span class="badge badge-success">Unlocked</span>
                                            }
                                        }
                                </td>
                                <td class="project-actions text-right">
                                    <a asp-area="Admin" asp-controller="User" asp-action="Details" asp-route-id="@Model[i].Id" class="btn btn-primary btn-sm">
                                        <i class="fas fa-user"></i>
                                        Profile
                                    </a>
                                    <a asp-area="Admin" asp-controller="User" asp-action="Edit" asp-route-id="@Model[i].Id" class="btn btn-info btn-sm">
                                        <i class="fas fa-user-edit"></i>
                                        Edit
                                    </a>
                                        @{
                                            if (@Model[i].LockoutEnd is not null)
                                            {
                                            <form asp-area="Admin" asp-controller="User" asp-action="UnlockUser" asp-route-id="@Model[i].Id" method="post">
                                                <button type="submit" class="btn btn-success btn-sm">
                                                    <i class="fas fa-lock-open"></i>
                                                    Unlock
                                                </button>
                                            </form>
                                            }
                                            else
                                            {
                                            <form asp-area="Admin" asp-controller="User" asp-action="LockUser" asp-route-id="@Model[i].Id" method="post">
                                                <button type="submit" class="btn btn-danger btn-sm">
                                                    <i class="fas fa-lock"></i>
                                                    Lock
                                                </button>
                                            </form>
                                            }
                                        }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
    <br />
    <div class="card-footer">
        <nav aria-label="Contacts Page Navigation">
            @* Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount*@
            <ul class="pagination justify-content-center m-0" id="contentPager">   
                @*<li class="page-item active"><a class="page-link" href="#">999</a></li>*@
                <li class="page-item active">
                    
                        @Html.PagedListPager(
                        Model, page => Url.Action("UserGrid", new { page })
                        )
                </li>

            </ul>
        </nav>
    </div>
</div>
<!-- /.content-wrapper -->
<!-- /.control-sidebar -->
<!-- ./wrapper -->